### ISSUE TITLE
yaz_record on php7.1

### ISSUE THREAD

**Issue by Y-QiuJunHao** [indexdata/phpyaz#10]
On php7.1, yaz_record and yaz_error will get stuck after searching.
Found that in PHP_FUNCTION (yaz_record) and PHP_FUNCTION (yaz_error) need to add xfree (type_tmp); and release_assoc (p); can be executed normally

**Comment by adamdickmeiss** [comment]
yaz_record is calling xfree(type_tmp) already.
yaz_error does not have a local variable type_tmp
