### ISSUE TITLE
Compilation on Linux without yaz-config (Debian 11)

### ISSUE THREAD

**Issue by mahaesin** [indexdata/phpyaz#12]
Compilation fails on Debian 11 (bullseye) because yaz-config is not provided anymore (by debian's yaz-packages).

As a workaround i used following config.m4 file to obtain the yaz configuration values with pkg-config:
[config_m4.txt](https://github.com/indexdata/phpyaz/files/6790761/config_m4.txt)

Can / should pkg-config be added as fallback (or added as default falling back to yaz-config)?

**Comment by adamdickmeiss** [comment]
Fixed

https://github.com/indexdata/phpyaz/pull/14
