### ISSUE TITLE
PHP8 release for pecl

### ISSUE THREAD

**Issue by eimantaaas** [indexdata/phpyaz#16]
Do you plan to release new version which can be installed via pecl on PHP8?

**Comment by Remgax** [comment]
I support this idea. I would like to use phpyaz with Symfony 6.1 version which requires PHP 8.1+.

**Comment by dsenalik** [comment]
I wrote instructions on how to install the current development version, which works with PHP8. Find them here https://github.com/tripal/tripal/issues/1287#issuecomment-1220860200

**Comment by dsenalik** [comment]
Thank you Peter!

**Comment by dltj** [comment]
Thank you, @dsenalik! I have a release drafted for @adamdickmeiss to review before making a formal release for this plus everything else that was on master.
