### ISSUE TITLE
Version 1.2.4 won't build

### ISSUE THREAD

**Issue by eshicks4** [indexdata/phpyaz#19]
Yaz 5.31.1 is installed into /usr/local

[root@929e9a22e810 yaz-1.2.4]# ./configure --with-php-config=/usr/local/bin/php-config --with-yaz=/usr/local
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/20200930
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... gawk
checking for YAZ support... yes, shared
configure: error: YAZ not found (missing )

**Comment by ryandesign** [comment]
What does the config.log say about why yaz was not found?

**Comment by adamdickmeiss** [comment]
Current version relies on pkg-config to determine location of yaz development libraries.

Changed check to be more informative with #21
