### ISSUE TITLE
No prebuilt DLLs for PHP 7.1

### ISSUE THREAD

**Issue by gronostajo** [indexdata/phpyaz#5]
Hello. I'm currently developing an application using PHP 7.1 and I need Z39.50 support. I found prebuilt DLLs for PHP 5.6 and 7.0 [here](http://ftp.indexdata.dk/pub/phpyaz/windows/), but neither of these will do.

Could you please build DLLs for PHP 7.1 or provide me with some resources on how I can do it? I have no prior experience working with PHP extensions.

Thanks in advance.

**Comment by adamdickmeiss** [comment]
It's a couple of hours work.. Here are DLLs for 32-bit
http://ftp.indexdata.dk/pub/phpyaz/windows/vc14/x86/php-7.1/
I can't get VC2015 to create 64-bit binaries anymore. Probably need to re-install VS, which I don't have time for.

**Comment by gronostajo** [comment]
Thank you very much!
